name: ESLint

on: [push]

jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Modules
        run: npm install eslint
      - name: Run ESLint
        run: npm eslint . --ext .jsx,.ts,.tsx
